In [72]:
import numpy as np 
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [73]:
def data_processing(filepath):
    movie_data = pd.read_csv("%s"%filepath, lineterminator='\n')
    return movie_data

In [74]:
movie_data= data_processing("../mymoviedb.csv")

In [75]:
movie_data

Release_Date                                 Title  \
0      2021-12-15               Spider-Man: No Way Home   
1      2022-03-01                            The Batman   
2      2022-02-25                               No Exit   
3      2021-11-24                               Encanto   
4      2021-12-22                        The King's Man   
...           ...                                   ...   
9822   1973-10-15                              Badlands   
9823   2020-10-01                      Violent Delights   
9824   2016-05-06                          The Offering   
9825   2021-03-31  The United States vs. Billie Holiday   
9826   1984-09-23                               Threads   

                                               Overview  Popularity  \
0     Peter Parker is unmasked and no longer able to...    5083.954   
1     In his second year of fighting crime, Batman u...    3827.658   
2     Stranded at a rest stop in the mountains durin...    2618.087   
3     The tale of an extraordinary family, the Madri...    2402.201   
4     As a collection of history's worst tyrants and...    1895.511   
...                                                 ...         ...   
9822  A dramatization of the Starkweather-Fugate kil...      13.357   
9823  A female vampire falls in love with a man she ...      13.356   
9824  When young and successful reporter Jamie finds...      13.355   
9825  Billie Holiday spent much of her career being ...      13.354   
9826  Documentary style account of a nuclear holocau...      13.354   

      Vote_Count  Vote_Average Original_Language  \
0           8940           8.3                en   
1           1151           8.1                en   
2            122           6.3                en   
3           5076           7.7                en   
4           1793           7.0                en   
...          ...           ...               ...   
9822         896           7.6                en   
9823           8           3.5                es   
9824          94           5.0                en   
9825         152           6.7                en   
9826         186           7.8                en   

                                   Genre  \
0     Action, Adventure, Science Fiction   
1               Crime, Mystery, Thriller   
2                               Thriller   
3     Animation, Comedy, Family, Fantasy   
4       Action, Adventure, Thriller, War   
...                                  ...   
9822                        Drama, Crime   
9823                              Horror   
9824           Mystery, Thriller, Horror   
9825               Music, Drama, History   
9826         War, Drama, Science Fiction   

                                             Poster_Url  
0     https://image.tmdb.org/t/p/original/1g0dhYtq4i...  
1     https://image.tmdb.org/t/p/original/74xTEgt7R3...  
2     https://image.tmdb.org/t/p/original/vDHsLnOWKl...  
3     https://image.tmdb.org/t/p/original/4j0PNHkMr5...  
4     https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...  
...                                                 ...  
9822  https://image.tmdb.org/t/p/original/z81rBzHNgi...  
9823  https://image.tmdb.org/t/p/original/4b6HY7rud6...  
9824  https://image.tmdb.org/t/p/original/h4uMM1wOhz...  
9825  https://image.tmdb.org/t/p/original/vEzkxuE2sJ...  
9826  https://image.tmdb.org/t/p/original/lBhU4U9Eeh...  

[9827 rows x 9 columns]

In [29]:
movie_data.iloc[0]["Poster_Url"]

'https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg'

In [17]:
selected_features = ["Title","Overview","Genre"]

In [19]:
for feature in selected_features:
    movie_data[feature] = movie_data[feature].fillna("")

In [20]:
combined_features = movie_data['Title'] + movie_data['Overview'] + movie_data['Genre']

In [22]:
vectorizer = TfidfVectorizer()

In [23]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [25]:
feature_vectors

<1x37873 sparse matrix of type '<class 'numpy.float64'>'
	with 47 stored elements in Compressed Sparse Row format>

In [26]:
similarity = cosine_similarity(feature_vectors)

In [27]:
print(similarity)

[[1.         0.01823752 0.04800248 ... 0.02406536 0.05123007 0.02672762]
 [0.01823752 1.         0.02966971 ... 0.04399952 0.01907585 0.03171927]
 [0.04800248 0.02966971 1.         ... 0.06534234 0.06408315 0.02493957]
 ...
 [0.02406536 0.04399952 0.06534234 ... 1.         0.05840019 0.00969232]
 [0.05123007 0.01907585 0.06408315 ... 0.05840019 1.         0.04645969]
 [0.02672762 0.03171927 0.02493957 ... 0.00969232 0.04645969 1.        ]]


In [30]:
movie_name = "iron man"

In [33]:
list_of_all_titles = movie_data["Title"].tolist()

In [34]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

In [35]:
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [36]:
close_match = find_close_match[0]

In [37]:
print(close_match)

Iron Man


In [60]:
index_of_movie = movie_data[movie_data.Title==close_match]

In [61]:
index_of_movie = index_of_movie.index.tolist()[0]

In [56]:
print(similarity[427])

[0.04723947 0.00730913 0.01047019 ... 0.01549144 0.02306413 0.02498562]


In [62]:
similarity_score = list(enumerate(similarity[index_of_movie]))

In [63]:
print(similarity_score)

[(0, 0.0472394745365771), (1, 0.007309133382921449), (2, 0.010470185902683202), (3, 0.04135492790069724), (4, 0.021839817297219087), (5, 0.016874163306716414), (6, 0.006917678401766617), (7, 0.003413229755782599), (8, 0.04329199739988836), (9, 0.034684404099713254), (10, 0.007865591429361192), (11, 0.02084460142932549), (12, 0.019604022739154035), (13, 0.0), (14, 0.013412927281806243), (15, 0.008172749886437862), (16, 0.008808806492422905), (17, 0.02824260926955611), (18, 0.011633843037707186), (19, 0.006546821553126753), (20, 0.006924411586358065), (21, 0.007413461262609087), (22, 0.03414786028496765), (23, 0.04537207392077197), (24, 0.05849389974398628), (25, 0.008529222323569202), (26, 0.012735158963831797), (27, 0.014296749213018047), (28, 0.008426180398380001), (29, 0.013965860150021516), (30, 0.016259253013737204), (31, 0.015846998084073437), (32, 0.004708573551445571), (33, 0.011792891490657039), (34, 0.003285645808779858), (35, 0.0), (36, 0.008766156131909855), (37, 0.010638127

In [68]:
sorted_similarity_score = sorted(similarity_score, key = lambda x:x[1], reverse = True)

In [69]:
print(sorted_similarity_score)

[(427, 1.0000000000000002), (204, 0.23556673813399104), (445, 0.22258406711969309), (4570, 0.1662222068016024), (2696, 0.14803636520243302), (254, 0.1480301390691336), (168, 0.12943629950198726), (4644, 0.12392029213539381), (6089, 0.1132174634509302), (3361, 0.11160297691281638), (7928, 0.11139668748986148), (5957, 0.11121556085683254), (6542, 0.10960672859861917), (2170, 0.10936349315008147), (7045, 0.10854148636503093), (8649, 0.10808696339751236), (7369, 0.10733971651828418), (2522, 0.10431107046299058), (6717, 0.10399473570606858), (3676, 0.10326745244955288), (757, 0.10138230446310495), (812, 0.10130076321772126), (5715, 0.09863762807290129), (188, 0.09858982212462446), (3109, 0.09719231933503003), (9599, 0.0956443645144426), (3343, 0.09395163335441668), (4007, 0.09211816399744488), (5812, 0.09163591626523442), (7177, 0.09145857933666893), (635, 0.09140599680630988), (4452, 0.09110008580875248), (2228, 0.09106139547812182), (4478, 0.09035054638418698), (7735, 0.0894058607664081),

In [71]:
i = 1
for movie in sorted_similarity_score:
    index = movie[0]
    title = movie_data[movie_data.index == index]["Title"].values[0]
    if (i < 30):
        print(i, title)
        i += 1


1 Iron Man
2 Iron Man 2
3 Iron Man 3
4 The Invincible Iron Man
5 Clown
6 Avengers: Age of Ultron
7 Spider-Man: Homecoming
8 Cradle 2 the Grave
9 Iron Sky: The Coming Race
10 LEGO Marvel Super Heroes: Avengers Reassembled!
11 Married to the Mob
12 Iron Man & Hulk: Heroes United
13 Escaflowne: The Movie
14 Time Trap
15 Shut In
16 The Disappearance of Alice Creed
17 Girl in the Box
18 The Shape of Water
19 Iron Monkey
20 Assassin 33 A.D.
21 The New Mutants
22 Kabaneri of the Iron Fortress: The Battle of Unato
23 Missing in Action
24 Black Water: Abyss
25 Iron Man & Captain America: Heroes United
26 Pooka!
27 Kung Fu Yoga
28 The Little Vampire
29 Iron Man: Rise of Technovore
